### ISSUE TITLE
Can't delete thumbnail

### ISSUE THREAD

**Issue by mmarseu** [admin-shell/aasx-package-explorer#11]
When trying to delete the thumbnail under Supplementary Files and then saving the package it fails with an error:
`Error When saving AASX, an error occurred: While write AASX C:\Users\hmrm\OneDrive - Festo\Documents\Verwaltungsschale\CP-AM-iDRILL2.aasx at \AssetAdministrationShellSDK.cs:line 2386 gave: Not able to delete pending file /thumbnail.jpg in saving package C:\Users\hmrm\OneDrive - Festo\Documents\Verwaltungsschale\CP-AM-iDRILL2.aasx  at \AssetAdministrationShellSDK.cs:line 2459`

**To Reproduce**
1. Open [ThumbnailBugRepro.zip](https://github.com/admin-shell/aasx-package-explorer/files/2987068/ThumbnailBugRepro.zip)
2. Go to edit mode
3. Delete Thumbnail
4. Save package

**Comment by admin-shell** [comment]
I've changed to code some 10days ago; should now work.
