### ISSUE TITLE
Mouse DoubleClick opens "Show Content" automatically (if valid).

### ISSUE THREAD

**Issue by aorzelskiGH** [admin-shell/aasx-package-explorer#13]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by admin-shell** [comment]
Added. Mouse DoubleClick opens "Show Content" automatically, if content present.
Please check this feature.
Remark: code changes tagged with //MIHO1 for traceability

**Comment by admin-shell** [comment]
I think it's closed. Please open, if bugs are showing up.
