### ISSUE TITLE
Thumbnail shall be per AAS

### ISSUE THREAD

**Issue by aorzelskiGH** [admin-shell/aasx-package-explorer#14]
Today the thumbnail is for the package, which is fine, if only 1 AAS is in the package.
But with several AAS each AAS shall have a thumbnail.
This is also implied by the graphical picture on the left and by the dynamic changing of AAS id and asset id, i.e. the picture shall also change accordingly.

![Several AAS in a package](https://user-images.githubusercontent.com/48956800/59928608-66cbe600-943f-11e9-9c53-8e31a96b61e8.JPG)

**Comment by Joy2233** [comment]
I agree with this. Hope that thumbnail can be added for each AAS. Besides, the picture on the left would be missing if one AAS is associated with multiple assets.

**Comment by BirgitBoss** [comment]
thumbnail is added to the metamodel in V3.0RC01 

For further updates and new issues please go for [admin-shell-io: ](https://github.com/admin-shell-io/aasx-package-explorer)

**Comment by BirgitBoss** [comment]
> I agree with this. Hope that thumbnail can be added for each AAS. Besides, the picture on the left would be missing if one AAS is associated with multiple assets.

The metamodel does not support the association of more than one asset to an AAS.

**Comment by BirgitBoss** [comment]
Issues transferred to https://github.com/admin-shell-io/temp-aasx-package-explorer/issues/10. Closed here.
