### ISSUE TITLE
When copying recursively also copy the qualifiers

### ISSUE THREAD

**Issue by aorzelskiGH** [admin-shell/aasx-package-explorer#18]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by BirgitBoss** [comment]
In the meanwhile this seems to be fixed: at least in the V2.0-version qualifiers are copied (recursively and also for single elements) ==> can be closed?

**Comment by BirgitBoss** [comment]
I close the issue, for any new issues please go to admin-shell-io/aasx-package-explorer.
