### ISSUE TITLE
How to import ConceptDescriptions from ecl@ss

### ISSUE THREAD

**Issue by Joy2233** [admin-shell/aasx-package-explorer#20]
I put eclass folder under public-release-with-browser folder but doesn't work.

**Comment by JensPfeifle** [comment]
Try this:
Copy the relevant eclass XML files directly into a folder called `eclass` in the `public-release-with-browser` folder. 
Start the AASX Explorer with `AasxPackageExplorer.exe -eclass .\eclass\`

**Comment by Joy2233** [comment]
Yes it works now. Thank you for the clarification.
