### ISSUE TITLE
How should I query AASX repository

### ISSUE THREAD

**Issue by Joy2233** [admin-shell/aasx-package-explorer#21]
I follow the instruction to query the repository but the program exited without warning.

**Comment by BirgitBoss** [comment]
Did you set the parameter **-aasxrepo** when calling aasx-explorer.exe in .bat or (depending on the version you use)  "**AasxRepositoryFn": "..\\aasxrepo.json"** in options.json?

see
https://github.com/admin-shell/aasx-package-explorer/blob/master/help/index.md

Then it does not crash any longer when calling "Query aasx repository".
Before calling it you should of course first generate a corresponding repository.

**Comment by BirgitBoss** [comment]
I close the issue, for any new issues please go to admin-shell-io/aasx-package-explorer.
