### ISSUE TITLE
Bug in XML serialization of qualifiers

### ISSUE THREAD

**Issue by JensPfeifle** [admin-shell/aasx-package-explorer#26]
Please see the example below, taken directly from an AASX package created by the AASX Package Explorer (Build 190930).
In the XML serialization of the AAS, shouldn't the element which contains the qualifiers be `<aas:qualifiers>`? Unless I am misunderstanding the specification from VWSiD?

I propose to change line 2373 in `AssetAdministrationShellSDK.cs` from
`[XmlArray("qualifier")]`
to: \
`[XmlArray("qualifiers")]`

This change would probably break existing AASX packages. These would need to be either upgraded manually, or automatically by the AASX Package Explorer? 

I'd be happy to submit a pull request to this repository for this and other issues...

### Example AAS Snippet
```
<aas:submodel>
      <aas:idShort>AxisUtilization</aas:idShort>
      <aas:description>
        <aas:langString lang="EN">Submodel which contains runtime data</aas:langString>
      </aas:description>
      <aas:identification idType="URI">wbk.kit.edu/submodels/1/1/740EDD761C3F0114</aas:identification>
      <aas:semanticId>
        <aas:keys />
      </aas:semanticId>
      <aas:kind>Instance</aas:kind>
      <aas:qualifier>
        <aas:qualifier>
          <aas:qualifierType>OPCURL</aas:qualifierType>
          <aas:qualifierValue>opc.tcp://192.168.0.199:4840</aas:qualifierValue>
        </aas:qualifier>
        <aas:qualifier>
          <aas:qualifierType>OPCNamespace</aas:qualifierType>
          <aas:qualifierValue>2</aas:qualifierValue>
        </aas:qualifier>
        ...more qualifiers...
      </aas:qualifier>
      <aas:submodelElements>
        ...rest of submodel...
</aas:submodel>
```

**Comment by BirgitBoss** [comment]
see https://github.com/admin-shell-io/aasx-package-explorer/issues/264 for the same issue

This one can be closed.

**Comment by JensPfeifle** [comment]
Thanks
