### ISSUE TITLE
Explorer closed unexpected

### ISSUE THREAD

**Issue by adlergfx** [admin-shell/aasx-package-explorer#28]
**Describe the bug**
Created Project using the Explorer. Failed to reload. No error description or exception. I started the application using console but no output there. 

Project is attached and only renamed to zip
[blacky.zip](https://github.com/admin-shell/aasx-package-explorer/files/4070473/blacky.zip)

**To Reproduce**
1. load attached project

**Desktop (please complete the following information):**
 - OS: Windows 10 - x64

**Additional context**

**Comment by aorzelskiGH** [comment]
Hi, I tried it with source and debugger. It seems that the .AASX is really corrupted. This sometimes happens and only an earlier backup helps. Sorry, that I can not help.

Do you want to join the gitlab-Projekt and search for the problem by yourself with the source code?

**Comment by RAMI40** [comment]
> Hi, I tried it with source and debugger. It seems that the .AASX is really corrupted. This sometimes happens and only an earlier backup helps. Sorry, that I can not help.
> 
> Do you want to join the gitlab-Projekt and search for the problem by yourself with the source code?

Hello,  

I am currently working with AAS, AML and OPC UA.  

Is there a possibilty to join gitlab-Projekt. Thank you in advance for your time and cooperation. 

Best Regards

**Comment by admin-shell** [comment]
Please send me your email address so that I can enter you into the gitlab project.

**Comment by admin-shell** [comment]
Please send me an email to aorzelski@phoenixcontact.com

**Comment by RAMI40** [comment]
> Please send me an email to [aorzelski@phoenixcontact.com](mailto:aorzelski@phoenixcontact.com)

Thank you for your response. I have mailed you via my E-mail  

Best Regards

**Comment by adlergfx** [comment]
Hey,

sorry that i am answering this late. Yes, i woul like to support your
project and could search by myself for the issue. Currently i am a little
busy because i just started a new job an now we have COVID but i would
realy like to help

Please grant access and i will take time for it and send you a patch if i
find something.

Greetings

Simon

**Comment by BirgitBoss** [comment]
I close the issue, for any new issues please go to admin-shell-io/aasx-package-explorer.
