### ISSUE TITLE
Import from AML does not work

### ISSUE THREAD

**Issue by swaytz** [admin-shell/aasx-package-explorer#29]
I am trying to import the AML file into the aasx. But it does not seem to recognize the elements. Is there a user guide/ rules as to how the AMl should be structured for importing into the AASX.  I tried to add the basic attributes to the instance hierarchy in AMl. (idShort, category, administration,etc). Yet it does recognize the AML elements.

**Comment by BirgitBoss** [comment]
Hi, if you are starting with AML then 
AutomationML Association: “Application Recommendations: Asset Administration Shell Representation (AR 004E) “, Version 1.0.0, 20.11.2019, [Online]. Available: https://www.automationml.org/o.red.c/dateien.html.
is the correct reference to know how a correct specification looks like.
 
The easier way to get a feeling is to start with an aasx file and export AML and then import it to an AML viewer. For this https://www.plattform-i40.de/PI40/Redaktion/EN/Downloads/Publikation/Details-of-the-Asset-Administration-Shell-Part1.html is the basis (see chapter on AutomationML Mapping and Appendix on AutomationML Mapping). Or just start editing in the aasx explorer...

**Comment by BirgitBoss** [comment]
I am closing the issue, please feel free to report further issues in https://github.com/admin-shell-io/aasx-package-explorer
