### ISSUE TITLE
Submodel copy has wrong property valueTypes

### ISSUE THREAD

**Issue by mmarseu** [admin-shell/aasx-package-explorer#3]
When copying a submodel from an auxiliary AAS, the resulting properties get the wrong valueType. valueType is actually filled with the same content as value.

**To Reproduce**
1. Create new package
2. Open sample AAS as auxiliary AAS
3. Create new AAS and asset in empty package
4. Copy the documentation submodel over from the sample AAS
5. Inspect any property in the submodel, e.g. DocFilename

**Expected behavior**
The property should have the same valueType as the original.

**Screenshots**
![image](https://user-images.githubusercontent.com/47556460/52630190-dfcc9700-2ebb-11e9-9e9d-7b6843809db7.png)

**Comment by admin-shell** [comment]
Fixed.
