### ISSUE TITLE
the Explorer used as a remote Rest Server

### ISSUE THREAD

**Issue by qirchseu** [admin-shell/aasx-package-explorer#32]
Hi.
I used the Explorer as a Rest server. The test was done in one PC, but, it seems like there is no remote server function.
Will there be a function as a remote server in future? Thank you.

**Comment by mySCHOTT** [comment]
Just look at [https://github.com/admin-shell/aasx-package-explorer/issues/31](url), how to use the **Net46AasxServerPlugin.dll**

Keep in mind, the implementation / function calls are not standardsized. It is just some ideas by the author of the AasxPackageExplorer!
###########################################
(1) Start REST: 
![AasxPackageExplorer_Build191121_REST_01](https://user-images.githubusercontent.com/61832356/78131648-b3efd600-741b-11ea-9b13-4f9db013f24c.png)

![AasxPackageExplorer_Build191121_REST_02](https://user-images.githubusercontent.com/61832356/78131664-b94d2080-741b-11ea-9947-d6fc3e89e056.png)

(2) Start REST client such as POSTMAN:
![AasxPackageExplorer_Build191121_REST_03](https://user-images.githubusercontent.com/61832356/78131706-cbc75a00-741b-11ea-9a02-7db16e85edb7.png)

(3) REST log:
[AasxPackageExplorer_Build191121_REST_Log.txt](https://github.com/admin-shell/aasx-package-explorer/files/4414726/AasxPackageExplorer_Build191121_REST_Log.txt)
 
(4) current REST api calls:
```
GET ^/aas/(id|([^/]+))(|/core|/complete|/thumbnail|/aasenv)(/|)$ > AasxRestServerLibrary.AasxRestServer+TestResource.GetAasAndAsset
PUT ^/aas(/|)$ > AasxRestServerLibrary.AasxRestServer+TestResource.PutAas
DELETE ^/aas/([^/]+)(/|)$ > AasxRestServerLibrary.AasxRestServer+TestResource.DeleteAasAndAsset
GET ^/handles/identification(/|)$ > AasxRestServerLibrary.AasxRestServer+TestResource.GetHandlesIdentification
POST ^/handles/identification(/|)$ > AasxRestServerLibrary.AasxRestServer+TestResource.PostHandlesIdentification
GET ^/server/profile(/|)$ > AasxRestServerLibrary.AasxRestServer+TestResource.GetServerProfile
GET ^/assets/([^/]+)(/|)$ > AasxRestServerLibrary.AasxRestServer+TestResource.GetAssets
PUT ^/assets(/|)$ > AasxRestServerLibrary.AasxRestServer+TestResource.PutAssets
GET ^/aas/(id|([^/]+))/submodels(/|)$ > AasxRestServerLibrary.AasxRestServer+TestResource.GetSubmodels
PUT ^/aas/(id|([^/]+))/submodels(/|)$ > AasxRestServerLibrary.AasxRestServer+TestResource.PutSubmodel
DELETE ^/aas/(id|([^/]+))/submodels/([^/]+)(/|)$ > AasxRestServerLibrary.AasxRestServer+TestResource.DeleteSubmodel
GET ^/aas/(id|([^/]+))/submodels/([^/]+)(|/core|/deep|/complete)(/|)$ > AasxRestServerLibrary.AasxRestServer+TestResource.GetSubmodelContents
GET ^/aas/(id|([^/]+))/submodels/([^/]+)/table(/|)$ > AasxRestServerLibrary.AasxRestServer+TestResource.GetSubmodelContentsAsTable
GET ^/aas/(id|([^/]+))/submodels/([^/]+)/elements(/([^/]+)){1,99}?(|/core|/complete|/deep|/file|/blob|/events|/property)(/|)$ > AasxRestServerLibrary.AasxRestServer+TestResource.GetSubmodelElementsContents
POST ^/aas/(id|([^/]+))/submodels/([^/]+)/elements(/([^/]+)){1,99}?/invoke(/|)$ > AasxRestServerLibrary.AasxRestServer+TestResource.PostSubmodelElementsContents
PUT ^/aas/(id|([^/]+))/submodels/([^/]+)/elements(/([^/]+)){0,99}?(/|)$ > AasxRestServerLibrary.AasxRestServer+TestResource.PutSubmodelElementsContents
DELETE ^/aas/(id|([^/]+))/submodels/([^/]+)/elements(/([^/]+)){0,99}?(/|)$ > AasxRestServerLibrary.AasxRestServer+TestResource.DeleteSubmodelElementsContents
GET ^/aas/(id|([^/]+))/cds(/|)$ > AasxRestServerLibrary.AasxRestServer+TestResource.GetCds
PUT ^/aas/(id|([^/]+))/cds(/|)$ > AasxRestServerLibrary.AasxRestServer+TestResource.PutConceptDescription
GET ^/aas/(id|([^/]+))/cds/([^/]+)(/|)$ > AasxRestServerLibrary.AasxRestServer+TestResource.GetSpecificCd
DELETE ^/aas/(id|([^/]+))/cds/([^/]+)(/|)$ > AasxRestServerLibrary.AasxRestServer+TestResource.DeleteSpecificCd
```

**Comment by mySCHOTT** [comment]
(1) POSTMAN
`http://localhost:1111/handles/identification/`

(2) aasx MessageLog:
```
TRC: Listening: http://localhost:1111/
WRN: Please notice: the API and REST routes implemented in this version of the source code are not specified and standardised by thespecification Details of the Administration Shell. The hereby stated approach is solely the opinion of its author(s).
INF: Routing Request  : a4c106d931b9 - GET /handles/identification/ has 1 routes
TRC: Route Invoked    : a4c106d931b9 - 1/1 AasxRestServerLibrary.AasxRestServer+TestResource.GetHandlesIdentification
TRC: Routing Complete : a4c106d931b9 - 1 of 1 routes invoked
```

(3) BUT in POSTMAN getting no response for the request?!?
![AasxPackageExplorer_Build191121_REST_04](https://user-images.githubusercontent.com/61832356/78142360-21583280-742d-11ea-8e36-3c68289807fa.png)

**Comment by mySCHOTT** [comment]
Using **02_Bosch.aasx** in **AasxPackageExplorer**:

GET:
`http://localhost:1111/aas/Bosch_NexoPistolGripNutrunner`

RESPONSE:
```
{
    "AAS": {
        "hasDataSpecification": null,
        "derivedFrom": null,
        "asset": {
            "keys": [
                {
                    "type": "Asset",
                    "local": true,
                    "value": "http://dc-qr.com?m=0608842005&s=917004878",
                    "index": 0,
                    "idType": "URI"
                }
            ]
        },
        "submodels": [
            {
                "keys": [
                    {
                        "type": "Submodel",
                        "local": true,
                        "value": "http://boschrexroth.com/shells/0608842005/917004878/submodels/nameplate",
                        "index": 0,
                        "idType": "URI"
                    }
                ]
            },
            {
                "keys": [
                    {
                        "type": "Submodel",
                        "local": true,
                        "value": "http://boschrexroth.com/shells/0608842005/917004878/submodels/document",
                        "index": 0,
                        "idType": "URI"
                    }
                ]
            },
            {
                "keys": [
                    {
                        "type": "Submodel",
                        "local": true,
                        "value": "http://boschrexroth.com/shells/0608842005/917004878/submodels/service",
                        "index": 0,
                        "idType": "URI"
                    }
                ]
            },
            {
                "keys": [
                    {
                        "type": "Submodel",
                        "local": true,
                        "value": "http://boschrexroth.com/shells/0608842005/917004878/submodels/identification",
                        "index": 0,
                        "idType": "URI"
                    }
                ]
            }
        ],
        "conceptDictionaries": [],
        "identification": {
            "idType": "URI",
            "id": "http://boschrexroth.com/shells/0608842005/917004878"
        },
        "administration": null,
        "idShort": "Bosch_NexoPistolGripNutrunner",
        "category": null,
        "modelType": {
            "name": "AssetAdministrationShell"
        },
        "descriptions": null
    },
    "Asset": {
        "hasDataSpecification": null,
        "assetIdentificationModelRef": null,
        "identification": {
            "idType": "URI",
            "id": "http://dc-qr.com?m=0608842005&s=917004878"
        },
        "administration": null,
        "idShort": "M0608842005_S917004878",
        "category": null,
        "modelType": {
            "name": "Asset"
        },
        "kind": "Instance",
        "descriptions": null
    }
}
```
![AasxPackageExplorer_Build191121_REST_05](https://user-images.githubusercontent.com/61832356/78144097-74cb8000-742f-11ea-9a08-90b6d4d14e61.png)

**Comment by qirchseu** [comment]
Thanks for the help.
I have done as the guide. The communication between server and client in a same PC is working well. 
![2](https://user-images.githubusercontent.com/44893038/78263184-35d32280-7534-11ea-92d8-0c24652ce921.png)
But the communication between different PCs fails. Even though the localhost IP address, 127.0.0.1, was used. The http error 400 is listed.
![7](https://user-images.githubusercontent.com/44893038/78263763-f35e1580-7534-11ea-8409-1f14d9305638.png)
 I searched the error on the web. Someone suggested to modify the 'hosts' file. I modified the 'hosts', but the error still happens.

**Comment by mySCHOTT** [comment]
Please try to run the application with **admin rights** as following:
`AasxPackageExplorer.exe -maximized -dll ..\AasxPlugInS\Net46AasxServerPlugin\Net46AasxServerPlugin.dll -resthost SDEMAIM101187 -restport 11112
`
![AasxPackageExplorer_Build191121_REST_10](https://user-images.githubusercontent.com/61832356/78332380-385f6780-7588-11ea-9367-52a623f24053.png)
Then you could map the REST server to your computername.

Please verify, that none remote access is blocked like by firewall settings. The REST server will start as configured:
![AasxPackageExplorer_Build191121_REST_11](https://user-images.githubusercontent.com/61832356/78332389-3bf2ee80-7588-11ea-9d28-5dc985f415d2.png)

No remote access from another computer tested, because currently in quarantine.
![AasxPackageExplorer_Build191121_REST_12](https://user-images.githubusercontent.com/61832356/78332398-3f867580-7588-11ea-9767-2c831d4ba6af.png)

**Comment by mySCHOTT** [comment]
If I understand well, they are using Grapevine as a REST server

Please find more information here:
[https://github.com/sukona/Grapevine/wiki](url)
