### ISSUE TITLE
Can't delete a sub model element of an ENT

### ISSUE THREAD

**Issue by johndeken** [admin-shell/aasx-package-explorer#37]
When I crate an ENT and I create SubmodelElement(s) I can not delete those

When I cretae a SubmoduleElement as port of a submodel I can delete this ENT
![image](https://user-images.githubusercontent.com/65314331/85856042-86ff5500-b7b7-11ea-9f5e-ae197ba0a39d.png)

But when I create a submodelElemnt for this ENT, I can not delete this new cretaed SubmodelElement

![image](https://user-images.githubusercontent.com/65314331/85857134-8cf63580-b7b9-11ea-8218-d92bbc3b1eb9.png)

**Comment by BirgitBoss** [comment]
In newer versions this feature was added. Please go to https://github.com/admin-shell/aasx-package-explorer/ for downloading newest version of aasx package explorer.

**Comment by BirgitBoss** [comment]
I close the issue, for any new issues please go to admin-shell-io/aasx-package-explorer.
