### ISSUE TITLE
Asset type/instance distinction

### ISSUE THREAD

**Issue by vojanbe** [admin-shell/aasx-package-explorer#38]
In the current build, the Kind of an Asset can only be "template" or "instance".
According to the metamodel this should be "type" and "instance". 
This error was reproduced in Version 1.9.8.1 and 1.9.8.3.
![image](https://user-images.githubusercontent.com/50904291/92073577-4f62e980-edb4-11ea-9fd2-70b9f306ddd8.png)

Thanks & best regards,
Bernd

**Comment by BirgitBoss** [comment]
This is true, I also reported it:
https://github.com/admin-shell-io/temp-aasx-package-explorer/issues/6

for new issues please go for https://github.com/admin-shell-io/aasx-package-explorer/

**Comment by Ayyubshaikh** [comment]
Are template and Kind not the same??..If not can anyone explain me the difference.
I am new to AAS and IIOT

**Comment by BirgitBoss** [comment]
Hi, @Ayyubshaikh the metamodel of the Asset Administration Shell distinguishes between asset kind and modeling kind. For assets we distinguish between asset types and asset instances, for submodels and submodels elements we distinguish between model templates and model instances. These are two very different things. 

You can have model instances for asset instances, e.g. the serial number 12345 is a model instance for an asset instance. But you can also have model instances, e.g. manufacturer companyX or max temperature range -50 ... 120 for an asset type.

A model template for an asset instance or asset type just tells you that the model instance should provide values for the element or elements listed in the template.
See e.g. the two newly published submodels templates https://www.plattform-i40.de/PI40/Redaktion/EN/Downloads/Publikation/Submodel_templates-Asset_Administration_Shell-digital_nameplate.html and https://www.plattform-i40.de/PI40/Redaktion/EN/Downloads/Publikation/Submodel_templates-Asset_Administration_Shell-Technical_Data.html

 Hope, this explanation helps.

**Comment by BirgitBoss** [comment]
I close the issue, for any new comments please go to admin-shell-io/temp-aasx-package-explorer#6

for new issues please go for https://github.com/admin-shell-io/aasx-package-explorer/

**Comment by BirgitBoss** [comment]
> Are template and Kind not the same??..If not can anyone explain me the difference.
> I am new to AAS and IIOT

You may also go to https://github.com/admin-shell-io/questions-and-answers for frequently asked questions.
