### ISSUE TITLE
Support assetIdentificationModel

### ISSUE THREAD

**Issue by mmarseu** [admin-shell/aasx-package-explorer#4]
The title pretty much says it all. 
The specification mentions an optional submodel under the Asset element that carries additional identifying information. This assetIdentificationModel is not supported by the explorer. You can't create such a submodel and an existing submodel in the XML is not displayed.

**Comment by BirgitBoss** [comment]
There is support of linking an existing submodel as assetIdentificationModel as part of the AAS specification. This is also how it is intended to be: any submodel can be the assetIdentificationModel: so far there is no decision which template it should follow.
==> this issued can be closed as resolved

**Comment by mmarseu** [comment]
I see that this feature has been added a while ago. Thanks for letting me know!
I'm closing the issue.
