### ISSUE TITLE
Broken hint for SubmodelElementCollection

### ISSUE THREAD

**Issue by mmarseu** [admin-shell/aasx-package-explorer#5]
The hint for the category field in a submodel element collection doesn't work. See screenshot: 
![image](https://user-images.githubusercontent.com/47556460/53074322-b8448280-34ea-11e9-8af2-1a266c13f906.png)

**To Reproduce**
Edit a submodel and add a SubmodelElementCollection

**Comment by admin-shell** [comment]
I've checked the code and cannot find a possible null pointer access. May be, in the meantime since 20FEB, I've fixed something here (have a faint remembering).

I leave it open for your re-evaluation with a new version of the software.

**Comment by mmarseu** [comment]
Where can I get the new version? Its not available for download here and the latest version on Sharepoint is from February 12.

**Comment by BirgitBoss** [comment]
newest version for V2.0
https://github.com/admin-shell/aasx-package-explorer/tree/master/builds/development/DataModelV2

I could not reproduce the broken hint: seems fine to me

**Comment by BirgitBoss** [comment]
I close the issue, for any new issues please go to admin-shell-io/aasx-package-explorer.
