### ISSUE TITLE
Stricter validation for idShort

### ISSUE THREAD

**Issue by mmarseu** [admin-shell/aasx-package-explorer#6]
The Asset Administration Shell specification states that idShort can only contain letters, digits and underscores. Also, it must start with a letter.

The editor doesn't check any of that. It didn't keep me from setting idShort as "401-test" for example. See the following screenshot as proof:
![screenshot](https://user-images.githubusercontent.com/47556460/53075286-13777480-34ed-11e9-968a-a633381779e3.png)

I would want the editor to stop me from saving such a change and display a message (possibly in the shape of a red hint bubble) telling me what I did wrong.

**Comment by admin-shell** [comment]
Changed to stricter check for all entities.
