### ISSUE TITLE
IEC 61360 STRING data type missing

### ISSUE THREAD

**Issue by mmarseu** [admin-shell/aasx-package-explorer#7]
When selecting a data type in an IEC 61360 data specification, the type STRING is missing from the drop down.

According to the [eClass wiki](http://wiki.eclass.eu/wiki/Value#Data_type_.28Value.29) there should be such a type.
In the drop down, however, the regular STRING (not STRING_TRANSLATABLE) is missing:
![image](https://user-images.githubusercontent.com/47556460/53084986-37918080-3502-11e9-849d-ae27e94b6237.png)

**Comment by admin-shell** [comment]
Have added this.
