### ISSUE TITLE
Save as AAS XML does not work

### ISSUE THREAD

**Issue by JoergWende** [admin-shell/aasx-package-explorer#8]
User: Jörg

  Steps to reproduce:load sample, select export as aas xml

  Expected results: <what should happen>

  Actual Results: <what was actually happening>

  Message: Error When saving AASX, an error occurred: Not able to handle C:\Users\IBM_ADMIN\Documents\1_IBM\2019\I40\VWSID\190214_AasxPackageExplorer\screencasts_communication\sample-admin-shell.xml.  at \AssetAdministrationShellSDK.cs:Zeile 2467..

Please consider attaching the AASX package (you might rename this to .zip), you were working on, as well as an screen shot.

Please mail your report to: michael.hoffmeister@festo.com
or you can directly add it at github: https://github.com/admin-shell/aasx-package-explorer/issues

**Comment by BirgitBoss** [comment]
I close the issue, ifvthere are still issues please go to admin-shell-io/aasx-package-explorer.
