### ISSUE TITLE
include schema names

### ISSUE THREAD

**Issue by JoergWende** [admin-shell/aasx-package-explorer#9]
**Is your feature request related to a problem? Please describe.**
The xml file does not contain any schema references - so it can't be validated completely. 

**Describe the solution you'd like**
Include the schema references

**Describe alternatives you've considered**
no alternate solutions

cheers
J.

**Comment by admin-shell** [comment]
In my experience, you have to tell very specific, where the schema is. Very often, URLs are used but we have no public accessable schema, yet. Or you put it locally. Put it to the package, as well??????

**Comment by JoergWende** [comment]
that is my example - you may have the files local to your xml file or in a local schema repository ...
J.
<aas:aasenv xmlns:aas="http://www.admin-shell.io/aas/1/0" xmlns:aas_common="http://www.admin-shell.io/aas_common/1/0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:IEC="http://www.admin-shell.io/IEC61360/1/0" xsi:schemaLocation="http://www.admin-shell.io/aas/1/0 AAS.xsd http://www.admin-shell.io/IEC61360/1/0 IEC61360.xsd>

**Comment by admin-shell** [comment]
For V2.0, I have re-visted this issue. All (updated) schemas are present inthe XML serialization. Joerg, please re-check and re-open, if necessary.

**Comment by jwende** [comment]
ok ... will check

**Comment by jwende** [comment]
what version to test ?
